[Improvement] * - Add SkipAuthRegex parameter to auth-proxy-ha-github…
widdix/aws-cf-templates pull request #521
Opened 2021-01-06 04:39 UTC by lwgordonimos

…-orga.yaml

---

This exposes the `skip_auth_regex` option of the `oauth2-proxy.cfg` file as a CloudFormation parameter.

https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#command-line-options
> bypass authentication for requests paths that match (may be given multiple times)

This should be suitably generic, but is to support a use case where I am running a Jenkins behind an auth proxy, but I want to selectively allow Github to post webhooks directly to Jenkins to notify of changes, and to trigger builds without having to rely on Jenkins polling when behind an auth proxy.

```yaml
    Parameters:
      SkipAuthRegex: '^\/github-webhook\/$'
```

2021-01-07 14:53 UTC, michaelwittig requested changes

2021-01-07 14:53 UTC, michaelwittig commented on security/auth-proxy-ha-github-orga.yaml
> +              - ## OAuth2 Proxy Config File
Could you be more explicit about the multi line string and start it with a `|`?

2021-01-07 14:53 UTC, michaelwittig commented
Thanks @lwgordonimos I added on comment

2021-01-14 05:55 UTC, lwgordonimos commented
@michaelwittig apologies, I missed this comment. I've now updated the template to restore the `|` to the multi line string.

2021-01-18 13:25 UTC, michaelwittig approved these changes

2021-01-18 13:25 UTC, merged

2021-01-18 13:26 UTC, michaelwittig commented
thanks @lwgordonimos