[Improvement] state/s3 - Support PublicWrite and PublicReadAndWrite Access
widdix/aws-cf-templates pull request #689
Opened 2023-06-12 15:42 UTC by michaelwittig

2023-06-12 19:05 UTC, andreaswittig requested changes

2023-06-12 19:05 UTC, andreaswittig commented on state/s3.yaml
> +          - HasPublicWriteAccess
@michaelwittig Should be `HasPublicReadAccess`?

2023-06-12 19:05 UTC, andreaswittig commented on state/s3.yaml
> +        - !If
@michaelwittig Is there a valid use case for public write?

2023-06-13 11:15 UTC, michaelwittig commented
tests passed

2023-06-28 09:07 UTC, andreaswittig approved these changes

2023-06-28 09:16 UTC, merged